### ISSUE TITLE
problems with #include <cuda.h>

### ISSUE THREAD

**Issue by abeltensor** [chewxy/cu#19]
I am trying to build this library on windows.  

I've got cuba 8 installed as well as cuDNN because I use tensorflow.  When I use go get on this library, I get a fatal error: `fatal error: cuda.h: No such file or directory`.

I don't have much experience with cgo, is there some flag that I have to pass to link the cuda library to this library so that I can build it?

**Comment by chewxy** [comment]
Are you on linux?

**Comment by chewxy** [comment]
Do you know where your CUDA is installed to?

**Comment by abeltensor** [comment]
yeah I know where cuda is installed

**Comment by chewxy** [comment]
You need to put these comments in:

```
//#cgo windows LDFLAGS:-LC:/cuda/vINSERTVERSIONHERE/lib/x64
//#cgo windows CFLAGS: -IC:/cuda/v5.0/include
import "C"
```

So say you are writing `main.go`: 

```
package main

//#cgo windows LDFLAGS:-LC:/cuda/vINSERTVERSIONHERE/lib/x64
//#cgo windows CFLAGS: -IC:/cuda/v5.0/include
import "C"
import (
"github.com/chewxy/cu"
"fmt"
)
fmt.Printf("CUDA version: %v\n", cu.Version())
	devices, _ := cu.NumDevices()
	fmt.Printf("CUDA devices: %v\n", devices)

	for d := 0; d < devices; d++ {
		name, _ := cu.Device(d).Name()
		cr, _ := cu.Device(d).Attribute(cu.ClockRate)
		mem, _ := cu.Device(d).TotalMem()
		maj, _ := cu.Device(d).Attribute(cu.ComputeCapabilityMajor)
		min, _ := cu.Device(d).Attribute(cu.ComputeCapabilityMinor)
		fmt.Printf("Device %d\n========\nName      :\t%q\n", d, name)
		fmt.Printf("Clock Rate:\t%v kHz\n", cr)
		fmt.Printf("Memory    :\t%v bytes\n", mem)
		fmt.Printf("Compute   : \t%d.%d\n", maj, min)
	}

```

p/s: the library would still work even if the go get command fails with the fatal error. As long as the library has been downloaded, it's fine.

**Comment by abeltensor** [comment]
Thank you for the advice.  With the advice I was finally able to get it to work.  

Here's basically the problem I encountered.  By default the windows cuda installer installs Cuda in a very awkward path; `c:\program files\Nvidia GPU Toolkit\cuda\v8.0\` was the path I had.  After seeing the flags you wanted me to put into the main.go file above, I tried hard coding the path into the main file with something like:
`//#cgo windows LDFLAGS:-LC:/program files/Nvidia GPU Toolkit/cuda/v8.0/lib/x64
//#cgo windows CFLAGS: -IC:/program files/Nvidia GPU Toolkit/cuda/v8.0/include`

This didn't work because of the spaces between the folder names.  Basically the compiler tried to find these paths but would stop at the space characters and assume each space was its own separate folder. I was given an error to that effect as well. 

After reinstalling Cuda into this path:  `c:/cuda/version/`, and then reinstalling your library I still got the error about the `cuda.h` header file.  I went into the cgoflags.go folder in your library and appended 
`-LC:/cuda/v8.0/lib/x64` and `-IC:/cuda/v8.0/include` and everything worked from there. 

I appreciate you giving me such detailed help it was your help that was able to point me towards the correct answer.  BTW I really like what I've seen of your library. 

P.S. As a suggestion, it might be worth adding v8.0 and perhaps even the v9.0 flags into your cgoflags.go file to avoid potential problems in the future since many people use Cuda v8.0 these days with tensorflow.

**Comment by chewxy** [comment]
Send a PR, and I'll even mark it `hacktoberfest` ! 

Thank you so much for your exploration and fixing of bugs!

**Comment by abeltensor** [comment]
Thank you for your patience and help!

**Comment by chewxy** [comment]
Hi, I'm wondering if we're gonna get that PR ;P

**Comment by abeltensor** [comment]
Sorry, I didn't see the PR response until just now.  

You want me to send a PR with the Cuda version numbers in the cgoflags.go file?

**Comment by chewxy** [comment]
If you would please... that'd be great. And I'll mark it hacktoberfest if you are participating

**Comment by abeltensor** [comment]
Alright, will do then.
